### ISSUE TITLE
Some questions about version and license

### ISSUE THREAD

**Issue by kennynaoh** [ngnjs/chassis-libx#1]
Hello @coreybutler ,
I am the member of [cndjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But I met some problems.

First,
I saw the version in `dist/chassis.x.min.js` is v1.0.17 on the 1.0.18 release [npm](https://www.npmjs.com/package/ngnx-chassis).
Please help me confirm this version inconsistent problem.

Second,
I saw the license you use is BSD, right?
What is the detail about the BSD?
Please reference [this](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json).

Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7943

**Comment by coreybutler** [comment]
This project is still under active development & doesn't yet meet the requirements of the CDNJS project. I would hold off on adding anything until we've reached a production state.
